
SELECT entrcs,
    TO_CHAR (BILSEQ),
    TO_CHAR (BILDATCLO, 'DD/MM/YYYY'),
    TO_CHAR (BILDUREE),
    TYPBILCOD,
    ORIBILCOD,
    SSORIBILCOD,
    CRCONF
FROM BILAN
WHERE    (MOD (INSTR ('10', etacod), 2) = 1)
     AND  entrcs = '482755741'
     AND (INSTR ('89', valcod) != 0)
     AND (MOD (INSTR ('SCSS', typbilcod), 2) = 1)
     AND (MOD (INSTR ('COECRCCSBLIN', oribilcod), 2) = 1)
ORDER BY BILDATCLO DESC, DECODE (MOD (INSTR ('COECRCCSBLIN', ORIBILCOD), 2), 1, INSTR('COECRCCSBLIN', ORIBILCOD), 9999);

SELECT
    VALUE AS ORACLE_CS_NAME,
    UTL_I18N.MAP_CHARSET(VALUE) AS IANA_VALUE
FROM V$NLS_VALID_VALUES
WHERE parameter = 'CHARACTERSET'
--  and UTL_I18N.MAP_CHARSET(VALUE) is not null
ORDER BY IANA_VALUE, VALUE;

alter session set nls_numeric_characters = '. ';

select * from nls_session_parameters;

select * from user_source where upper(text) like '%FUN_CONV_EURO%';


select bilclopre, count(*) from bileprod.bilan
where bildatclo > to_date('2015-01-01','YYYY-MM-DD')
group by bilclopre;


CREATE TABLE "BILEPROD"."BILAN"
   (	"BILSEQ" NUMBER(8,0) NOT NULL ENABLE,
	"TYPBILCOD" VARCHAR2(12 CHAR),
	"ENTRCS" VARCHAR2(10 CHAR) NOT NULL ENABLE,
	"RAPCOMCOD" VARCHAR2(12 CHAR),
	"MOTNONSAICOD" VARCHAR2(12 CHAR),
	"RAPGESCOD" VARCHAR2(12 CHAR),
	"GREFNUM" NUMBER(4,0),
	"NAFCOD" VARCHAR2(12 CHAR),
	"NUMCOD" VARCHAR2(12 CHAR),
	"ORIBILCOD" VARCHAR2(12 CHAR),
	"UNIMONCOD" VARCHAR2(12 CHAR),
	"CERCOD" VARCHAR2(12 CHAR),
	"QUALITCOD" VARCHAR2(12 CHAR),
	"ETACOD" VARCHAR2(12 CHAR),
	"VALCOD" VARCHAR2(12 CHAR),
	"VALGREFFECOD" VARCHAR2(12 CHAR),
	"ANNEXECOD" VARCHAR2(12 CHAR),
	"BILDATCLO" DATE NOT NULL ENABLE,
	"BILCLOPRE" VARCHAR2(3 CHAR),
	"BILDATCLON1" DATE,
	"BILCLOPREN1" VARCHAR2(3 CHAR),
	"BILDUREE" NUMBER(2,0),
	"BILPAQANN" VARCHAR2(4 CHAR),
	"BILPAQMAC" VARCHAR2(1 CHAR),
	"BILPAQINC" NUMBER(7,0),
	"BILNBCAR" NUMBER(10,0),
	"BILDURSAI" NUMBER(10,0),
	"BILNBCONFOR" NUMBER(10,0),
	"NUMGEST" VARCHAR2(11 CHAR),
	"NUMDEPOT" NUMBER(7,0),
	"NUMDATDEPOT" DATE,
	"NUMLOT" VARCHAR2(10 CHAR),
	"PRESAICOD" VARCHAR2(12 CHAR),
	"ORIDEVCOD" VARCHAR2(12 CHAR),
	"NAFCODSAV" VARCHAR2(12 CHAR),
	"APE08COD" VARCHAR2(12 CHAR),
	"SSTYPBILCOD" VARCHAR2(12 CHAR),
	"CRCONF" VARCHAR2(12 CHAR) DEFAULT 'NON' NOT NULL ENABLE,
	"SSORIBILCOD" VARCHAR2(12 CHAR),
	"CLIPRE" VARCHAR2(16 CHAR),
	"CLIREF" VARCHAR2(16 CHAR),
	 CONSTRAINT "PK_BILAN" PRIMARY KEY ("BILSEQ")
  USING INDEX PCTFREE 20 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 283115520 NEXT 20971520 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_IND_BILEPROD"  ENABLE NOVALIDATE,
	 CONSTRAINT "FK_BILAN_UNIMONCOD" FOREIGN KEY ("UNIMONCOD")
	  REFERENCES "BILEPROD"."UNIMONCOD" ("UNIMONCOD") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_BILAN_ORIDEVCOD" FOREIGN KEY ("ORIDEVCOD")
	  REFERENCES "BILEPROD"."ORIDEVCOD" ("ORIDEVCOD") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_APE08_BILAN" FOREIGN KEY ("APE08COD")
	  REFERENCES "BILEPROD"."ORT$_APE08COD" ("COD") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_BILAN_ANNEXECOD" FOREIGN KEY ("ANNEXECOD")
	  REFERENCES "BILEPROD"."ANNEXECOD" ("ANNEXECOD") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_BILAN_RAPCOMCOD" FOREIGN KEY ("RAPCOMCOD")
	  REFERENCES "BILEPROD"."RAPCOMCOD" ("RAPCOMCOD") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_BILAN_RAPGESCOD" FOREIGN KEY ("RAPGESCOD")
	  REFERENCES "BILEPROD"."RAPGESCOD" ("RAPGESCOD") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_BILAN_ETACOD" FOREIGN KEY ("ETACOD")
	  REFERENCES "BILEPROD"."ETACOD" ("ETACOD") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_BILAN_VALCOD" FOREIGN KEY ("VALCOD")
	  REFERENCES "BILEPROD"."VALCOD" ("VALCOD") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_BILAN_NAFCOD" FOREIGN KEY ("NAFCOD")
	  REFERENCES "BILEPROD"."NAFCOD" ("NAFCOD") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_BILAN_TYPBILCOD" FOREIGN KEY ("TYPBILCOD")
	  REFERENCES "BILEPROD"."TYPBILCOD" ("TYPBILCOD") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_BILAN_VALGREFFECOD" FOREIGN KEY ("VALGREFFECOD")
	  REFERENCES "BILEPROD"."VALGREFFECOD" ("VALGREFFECOD") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_BILAN_ORIBILCOD" FOREIGN KEY ("ORIBILCOD")
	  REFERENCES "BILEPROD"."ORIBILCOD" ("ORIBILCOD") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_BILAN_NUMCOD" FOREIGN KEY ("NUMCOD")
	  REFERENCES "BILEPROD"."NUMCOD" ("NUMCOD") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_BILAN_CERCOD" FOREIGN KEY ("CERCOD")
	  REFERENCES "BILEPROD"."CERCOD" ("CERCOD") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_BILAN_QUALITCOD" FOREIGN KEY ("QUALITCOD")
	  REFERENCES "BILEPROD"."QUALITCOD" ("QUALITCOD") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_BILAN_MOTNONSAICOD" FOREIGN KEY ("MOTNONSAICOD")
	  REFERENCES "BILEPROD"."MOTNONSAICOD" ("MOTNONSAICOD") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_BILAN_PRESAICOD" FOREIGN KEY ("PRESAICOD")
	  REFERENCES "BILEPROD"."PRESAICOD" ("PRESAICOD") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_BILAN_GREFNUM" FOREIGN KEY ("GREFNUM")
	  REFERENCES "BILEPROD"."GREFFE" ("GREFNUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_BILAN_SSTYPE" FOREIGN KEY ("SSTYPBILCOD")
	  REFERENCES "BILEPROD"."ORT$_SSTYPBILCOD" ("COD") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 20 PCTUSED 70 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2147483648 NEXT 52428800 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_TAB_BILEPROD"

